### ISSUE TITLE
I can't take several measures

### ISSUE THREAD

**Issue by Castaneira7** [thiezn/iperf3-python#37]
I would like to repeat the tests several times to relieve the bandwidth of an entire room. but when I repeat the test it gives me an error that I suppose is to rewrite the variable result = client.run ()

Traceback (most recent call last):
  File "/home/pi/Desktop/test1.py", line 19, in <module>
    test = client.run()
  File "/usr/local/lib/python3.5/dist-packages/iperf3-0.1.10-py3.5.egg/iperf3/iperf3.py", line 612, in run
    output_to_screen(self._stdout_fd, self._stderr_fd)  # enable stdout
  File "/usr/local/lib/python3.5/dist-packages/iperf3-0.1.10-py3.5.egg/iperf3/iperf3.py", line 80, in output_to_screen
    os.dup2(stdout_fd, 1)
OSError: [Errno 9] Bad file descriptor**_

any help??

**Comment by iamjarvs** [comment]
I hit this toady 'OSError: [Errno 9] Bad file descriptor' trying to run two tests in a singe function. My work around was.

```
def iperfSingleTest():
  <test setup> 
  result = client.run ()
  print(result)

def iperfManyTests():
  for i in range(1,3):
    iperfSingleTest()
```
Hope this helps
